apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  ports:
  - port: {{ .Values.mongodb.port }}
  selector:
    app: {{ .Release.Name }}-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
